# Generated by Django 5.1.6 on 2025-03-13 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='community',
        ),
    ]
