# Generated by Django 5.1.6 on 2025-03-13 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_feedback_community'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
    ]
