# Generated by Django 5.1.7 on 2025-03-15 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_managers_community_emoji_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='api_feedback',
        ),
    ]
