# Generated by Django 5.1.7 on 2025-03-16 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_feedback_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='id',
            new_name='feedback_id',
        ),
    ]
