# Generated by Django 5.1.7 on 2025-03-16 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_id_feedback_feedback_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='updated_at',
        ),
    ]
