# Generated by Django 5.1.7 on 2025-03-17 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_feedback_is_anonymous_feedback_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='emoji',
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_updates', models.BooleanField(default=True)),
                ('post_notifications', models.BooleanField(default=True)),
                ('announcements', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscribed_communities', models.ManyToManyField(blank=True, to='api.community')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_user_notification_preferences',
            },
        ),
    ]
