CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = False

SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_HTTPONLY = True

LOGOUT_REDIRECT_URL = None

# PRODUCTION
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True
