CSRF_COOKIE_SAMESITE = 'Strict'
SESSION_COOKIE_SAMESITE = 'Strict'
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_HTTPONLY = True

LOGOUT_REDIRECT_URL = None

# PRODUCTION
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True